services:
  - type: web
    name: ANNIE-X-MUSIC
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bash start"
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: "/"
    healthCheckPort: 10000
    autoDeploy: true
